pub mod dusty;
use crate::dusty::db::core::initialize_dusty;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_http::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_pty::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .max_file_size(50_000)
                .target(tauri_plugin_log::Target::new(
                    tauri_plugin_log::TargetKind::Stdout,
                ))
                .target(tauri_plugin_log::Target::new(
                    tauri_plugin_log::TargetKind::LogDir { file_name: None },
                ))
                .target(tauri_plugin_log::Target::new(
                    tauri_plugin_log::TargetKind::Webview,
                ))
                .build(),
        )
        .invoke_handler(tauri::generate_handler![
            dusty::api::git::get_git_info,
            dusty::api::filesystem::read_dir,
            dusty::api::filesystem::reveal_in_file_explorer,
            dusty::api::filesystem::read_file,
            dusty::api::filesystem::write_file,
            dusty::api::filesystem::append_file,
            dusty::api::filesystem::copy_file,
            dusty::api::filesystem::move_file,
            dusty::api::filesystem::rename_file,
            dusty::api::filesystem::delete_file,
            dusty::api::filesystem::create_directory,
            dusty::api::filesystem::delete_directory,
            dusty::api::filesystem::exists,
            dusty::api::filesystem::get_metadata,
            dusty::api::opener::open_file,
            dusty::api::opener::open_in_vs_code,
            dusty::api::opener::open_url,
            dusty::api::show::scan_shows,
            dusty::api::show::sync_scan_shows,
            dusty::api::show::rename_show,
            dusty::api::show::update_show_status,
            dusty::api::show::update_ban_status,
            dusty::api::show::update_pin_status,
            dusty::api::show::update_show_id,
            dusty::api::show::reset_shows_table,
            dusty::api::show::add_shows_to_db,
            dusty::api::project::scan_projects,
            dusty::api::project::sync_scan_projects,
            dusty::api::project::update_project_pin_status,
            dusty::api::project::update_project_status,
            dusty::api::project::update_project_tags,
            dusty::api::project::reset_project_table,
            dusty::api::project::scan_project_tags,
            dusty::api::media::get_media_of_type,
            dusty::api::media::sync_media_database,
            dusty::api::media::reset_media_cache_table,
            dusty::api::misc::scan_misc,
            dusty::api::misc::sync_scan_misc,
            dusty::api::misc::scan_misc_tree,
            dusty::api::misc::sync_scan_misc_tree,
            dusty::api::misc::reset_misc_cache_table,
            dusty::api::empty_dir::scan_empty_dir,
            dusty::api::empty_dir::sync_scan_empty_dir,
            dusty::api::lab::tokenize,
            dusty::api::lab::get_all_table_data,
            dusty::api::settings::reset_database,
            dusty::api::show::get_show_cache,
            dusty::api::show::upsert_show_cache,
            dusty::api::show::reset_show_cache,
            dusty::api::show::get_show_cache_key,
            dusty::api::table::get_all_tables,
            dusty::api::table::reset_table,
            dusty::api::table::resync_table,
            dusty::api::system::get_system_info,
            dusty::api::utility::get_coupling_value_between_query_and_result_title,
            dusty::api::overview::get_stats,
            dusty::api::music::scan_music,
            dusty::api::music::sync_scan_music,
            dusty::api::music::scan_music_cached,
            dusty::api::image::scan_image,
            dusty::api::image::sync_scan_image,
            dusty::api::video::scan_video,
            dusty::api::video::sync_scan_video,
            dusty::api::recent::add_recent_episode,
            dusty::api::recent::get_recent_episodes,
            dusty::api::recent::reset_recent_episodes_table,
            dusty::api::config::get_config_value,
            dusty::api::config::add_or_update_config_value,
            dusty::api::config::reset_config,
            dusty::api::terminal::get_available_terminals,
            dusty::api::terminal::open_terminal_at_path,
            dusty::api::user::get_user,
            dusty::api::user::save_user,
            dusty::api::user::update_display_name,
            dusty::api::user::update_avatar,
            dusty::api::user::reset_user,
            dusty::api::user::get_device_info,
            dusty::api::user::select_avatar_file,
            dusty::api::user::upload_avatar_from_path,
            dusty::api::core::page_changed,
            dusty::api::p2p::get_p2p_state,
            dusty::api::p2p::select_send_files,
            dusty::api::p2p::start_send,
            dusty::api::p2p::search_for_senders,
            dusty::api::p2p::get_pending_transfers,
            dusty::api::p2p::accept_transfer,
            dusty::api::p2p::reject_transfer,
            dusty::api::p2p::cancel_transfer,
        ])
        .setup(|app| {
            initialize_dusty(app)?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
